# Enable SPI and Display subsystems
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y

# Enable Character Framebuffer for easy bitmap/text drawing
CONFIG_CHARACTER_FRAMEBUFFER=y

# Heap
CONFIG_HEAP_MEM_POOL_SIZE=4096

# USB Console Settings
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Shell to play with OLED
CONFIG_SHELL=y
CONFIG_CHARACTER_FRAMEBUFFER_SHELL=y
