--[[
    Calibration Module
    Handles loading and saving of OSD gain/phase offsets.
]]

local Calibration = {}

local CAL_FILE = (_G.appPrefix or "") .. "config/calibration.lua"

function Calibration.init()
    -- Load existing calibration if present
    local ok, calData = pcall(require, "config.calibration")
    if not ok then
        print("[CAL] No config/calibration.lua found, using defaults (zero)")
        -- Create a default file if it doesn't exist
        Calibration.saveDefault()
        return
    end

    if type(calData) == "table" then
        print("[CAL] Loading stored calibration data")
        for i = 0, 1 do
            local ch = calData[i+1]
            if ch then
                if hw and hw.setCalibration then
                    hw.setCalibration(i, ch.gain or 0, ch.phase or 0, ch.align_r or 1.0, ch.align_i or 0.0)
                end
                print(string.format("  OSD%d: %+.3f dB, %+.2f deg | Align: %.4f + j%.4f", 
                    i, ch.gain or 0, ch.phase or 0, ch.align_r or 1.0, ch.align_i or 0.0))
            end
        end
    end
end

function Calibration.saveDefault()
    local f = io.open(CAL_FILE, "w")
    if f then
        f:write("return {\n")
        f:write("  { gain = 0.0, phase = 0.0, align_r = 1.0, align_i = 0.0 }, -- OSD0\n")
        f:write("  { gain = 0.0, phase = 0.0, align_r = 1.0, align_i = 0.0 }  -- OSD1\n")
        f:write("}\n")
        f:close()
    end
end

function Calibration.addResults(results)
    -- Append/Overwrite calibration file
    local f = io.open(CAL_FILE, "w")
    if f then
        f:write("-- Generated by NexRx Manual Calibration\n")
        f:write("return {\n")
        for i, res in ipairs(results) do
            f:write(string.format("  { gain = %.3f, phase = %.2f, align_r = %.4f, align_i = %.4f }, -- OSD%d\n", 
                res.gain, res.phase, res.align_r or 1.0, res.align_i or 0.0, i-1))
            -- Apply immediately
            if hw and hw.setCalibration then
                hw.setCalibration(i-1, res.gain, res.phase, res.align_r or 1.0, res.align_i or 0.0)
            end
        end
        f:write("}\n")
        f:close()
        print("[CAL] Saved new calibration to " .. CAL_FILE)
    end
end

return Calibration
