--[[\
    Calibration Module
    Handles loading and saving of QSD gain/phase offsets.
]]

local Calibration = {}

local CAL_FILE = "config/calibration.lua"

function Calibration.init()
    -- Load existing calibration if present
    local ok, calData = pcall(require, "config.calibration")
    if not ok then
        print("[CAL] No config/calibration.lua found, using defaults (zero)")
        -- Create a default file if it doesn't exist
        Calibration.saveDefault()
        return
    end

    if type(calData) == "table" then
        print("[CAL] Loading stored calibration data")
        for i = 0, 2 do
            local ch = calData[i+1]
            if ch then
                hw.setCalibration(i, ch.gain or 0, ch.phase or 0, ch.align_r or 0.5, ch.align_i or 0.0)
                print(string.format("  QSD%d: %+.3f dB, %+.2f deg | Align: %.4f + j%.4f", 
                    i, ch.gain or 0, ch.phase or 0, ch.align_r or 0.5, ch.align_i or 0.0))
            end
        end
    end
end

function Calibration.saveDefault()
    local f = io.open(CAL_FILE, "w")
    if f then
        f:write("return {\n")
        f:write("  { gain = 0.0, phase = 0.0, align_r = 0.5, align_i = 0.0 }, -- QSD0\n")
        f:write("  { gain = 0.0, phase = 0.0, align_r = 0.5, align_i = 0.0 }, -- QSD1\n")
        f:write("  { gain = 0.0, phase = 0.0, align_r = 1.0, align_i = 0.0 }  -- QSD2\n")
        f:write("}\n")
        f:close()
    end
end

function Calibration.addResults(results)
    -- Append/Overwrite calibration file
    local f = io.open(CAL_FILE, "w")
    if f then
        f:write("-- Generated by NexRx Manual Calibration\n")
        f:write("return {\n")
        for i, res in ipairs(results) do
            f:write(string.format("  { gain = %.3f, phase = %.2f, align_r = %.4f, align_i = %.4f }, -- QSD%d\n", 
                res.gain, res.phase, res.align_r or 0.5, res.align_i or 0.0, i-1))
            -- Apply immediately
            hw.setCalibration(i-1, res.gain, res.phase, res.align_r or 0.5, res.align_i or 0.0)
        end
        f:write("}\n")
        f:close()
        print("[CAL] Saved new calibration to " .. CAL_FILE)
    end
end

return Calibration
